# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Essentials
    avoid_print: true
    always_use_package_imports: true

    # Relax noisy style rules
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    unnecessary_null_checks: false
    prefer_final_locals: false
    sort_pub_dependencies: false
    # prefer_single_quotes: false  # leave off for flexibility

    # Keep useful runtime safety
    use_build_context_synchronously: true

analyzer:
  errors:
    # Downgrade style lints to info so they don't block you
    prefer_const_constructors: info
    prefer_const_literals_to_create_immutables: info
    unnecessary_null_checks: info
    prefer_final_locals: info
    sort_pub_dependencies: info
    unused_import: info
    unnecessary_import: info
    invalid_annotation_target: ignore
